version: "3.7"
services:
  postgres:
    image: postgres:13.3
    restart: always
    container_name: graphql-course-postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /Users/mk/Work/graphql-journey/graphql-basics/postgres:/var/lib/postgresql/pgdata
    ports:
      - 5433:5432
