type Query {
    greeting(name: String): String!
    users(range: Range): [User!]!
    me: User!
    posts: [Post!]!
    commentaries: [Commentary!]!
}

input Range {
    min: Int!
    max: Int!
}


type Post {
    id: ID!
    title: String!
    body: String!
    published: Boolean!
    author: User!
    commentaries: [Commentary!]!
}

type User {
    id: ID!
    name: String!
    email: String!
    age: Int!
    posts: [Post!]!
}


type Commentary {
    id: ID
    body: String!
    author: User!
}
